name: Slack
on:
  schedule:
    - cron: '*/30 * * * *'
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SITE_URL: https://v4.eccube-plugin.net

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run
        run: python main.py -v
        
     - name: Notify Slack
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: demo
          SLACK_COLOR: danger
          SLACK_TITLE: Death
          SLACK_MESSAGE: 'デモサイトが落ちてます。'          